# **"What is the relationship between specific post characteristics (like video duration, use of trending audio, posting time, and hashtag count) and the likelihood of a post achieving viral status on Social Media?"**

Instagram statistics



*   Demonstrate the relevance of these sources using initial exploration, such as summary statistics, schema inspection, or simple exploratory analysis.
Brief description of downloaded data and reflection on how well it matches requirements or how it is amenable to match the requirements.

* Profiling steps that should include a short description, the code to execute these, and an interpretation and critical discussion of the results with respect to the suitability of the dataset for addressing the analytical task.

* Discussion of the quality of the data relating to aspects to be considered during data preparation and analysis. It should refer to at least two different quality criteria per explored dataset, one beign
assessed positively and one assessed as problematic.

* Concluding paragraph that summarizes suitability and important points to take note of if the dataset is selected to be used.

# **DS1**

Instagram Post dataset (DS1) - [Instagram-Posts.csv](https://brightdata.com/cp/datasets/browse/gd_lk5ns7kz21pck8jpis?id=hl_6c69a494)

The dataset contains Instagram post data


Strengths:


*   Contains many useful post characteristics information. Including video duration, post content, hashtag, description,etc
*   Contains virality measuring performance metrics (likes, shares, comments, etc)
*   Linkable to comments via post_id for richer engagement.




Weakness


*   Data quality issues like negative likes values and extreme outliers

In [25]:
import pandas as pd
df = pd.read_csv('Instagram - Posts.csv')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   url                    1000 non-null   object
 1   user_posted            1000 non-null   object
 2   description            956 non-null    object
 3   hashtags               647 non-null    object
 4   num_comments           1000 non-null   int64
 5   date_posted            1000 non-null   object
 6   likes                  888 non-null    float64
 7   photos                 1000 non-null   object
 8   videos                 179 non-null    object
 9   location               276 non-null    object
 10  latest_comments        583 non-null    object
 11  post_id                1000 non-null   int64
 12  discovery_input        0 non-null      float64
 13  has_handshake          0 non-null      float64
 14  shortcode              1000 non-null   object
 15  content_type           1000 non-null   object
 16  pk                     1000 non-null   int64
 17  content_id             1000 non-null   object
 18  engagement_score_view  122 non-null    float64
 19  thumbnail              1000 non-null   object
 20  video_view_count       166 non-null    float64
 21  product_type           122 non-null    object
 22  coauthor_producers     107 non-null    object
 23  tagged_users           270 non-null    object
 24  video_play_count       106 non-null    float64
 25  followers              1000 non-null   int64
 26  posts_count            1000 non-null   int64
 27  profile_image_link     1000 non-null   object
 28  is_verified            1000 non-null   bool
 29  is_paid_partnership    1000 non-null   bool
 30  partnership_details    1000 non-null   object
 31  user_posted_id         1000 non-null   int64
 32  post_content           1000 non-null   object
 33  audio                  1000 non-null   object
 34  profile_url            1000 non-null   object
 35  videos_duration        231 non-null    object
 36  images                 1000 non-null   object
 37  alt_text               868 non-null    object
 38  photos_number          1000 non-null   int64
 39  audio_url              17 non-null     object
dtypes: bool(2), float64(6), int64(7), object(25)
memory usage: 299.0+ KB

In [27]:
df.sort_values(by='likes', ascending=False).head(10)

,url,user_posted,description,hashtags,num_comments,date_posted,likes,photos,videos,location,...,partnership_details,user_posted_id,post_content,audio,profile_url,videos_duration,images,alt_text,photos_number,audio_url
337,https://www.instagram.com/p/B-cRmb0o4aB,natgeo,"Photo by @estherhorvath, Caption by @dzalcman ...",NaN,4021,2020-04-01T14:35:17.000Z,425076.0,"[""https://scontent.cdninstagram.com/v/t51.2885...",NaN,NaN,...,"{""profile_id"":null,""profile_url"":null,""usernam...",787132,"[{""id"":""2277772919547594369"",""index"":0,""type"":...","{""audio_asset_id"":null,""ig_artist_id"":null,""ig...",https://www.instagram.com/natgeo,NaN,[],"Photo by National Geographic on April 01, 2020.",0,NaN
627,https://www.instagram.com/p/CpNAFPwvBM-,folkative,A new regulation for SMA and SMK students in K...,NaN,6158,2023-02-28T10:43:28.000Z,388806.0,"[""https://scontent-ord5-2.cdninstagram.com/v/t...",NaN,NaN,...,"{""profile_id"":null,""profile_url"":null,""usernam...",3225353704,"[{""id"":""3048092883320836926"",""index"":0,""type"":...","{""audio_asset_id"":null,""ig_artist_id"":null,""ig...",https://www.instagram.com/folkative,NaN,[],"Photo by FOLKATIVE™ on February 28, 2023.",0,NaN
412,https://www.instagram.com/p/C660WGGt_wD,f1,Michael’s first pole for Ferrari… and of cours...,"[""#F1"",""#ImolaGP""]",301,2024-05-13T18:40:54.000Z,216943.0,"[""https://scontent-ord5-3.cdninstagram.com/v/t...","[""https://scontent-ord5-2.cdninstagram.com/o1/...",NaN,...,"{""profile_id"":null,""profile_url"":null,""usernam...",1692820292,"[{""id"":""3367233888215104515"",""index"":0,""type"":...","{""audio_asset_id"":""365585753180860"",""ig_artist...",https://www.instagram.com/f1,"[{""url"":""https://scontent-ord5-2.cdninstagram....",[],NaN,0,NaN
156,https://www.instagram.com/p/C70jImKS6BE,dilsepaneer,"Public Mein Nhi Dekh Sakte, Dosto Ki Bheji Ree...",NaN,1799,2024-06-05T04:48:17.000Z,166294.0,"[""https://instagram.fsjc1-3.fna.fbcdn.net/v/t5...","[""https://instagram.fsjc1-3.fna.fbcdn.net/o1/v...",NaN,...,"{""profile_id"":null,""profile_url"":null,""usernam...",1270990526,"[{""alt_text"":null,""id"":""3383483742420705348"",""...","{""audio_asset_id"":""766958352298189"",""ig_artist...",https://www.instagram.com/dilsepaneer,"[{""url"":""https://instagram.fsjc1-3.fna.fbcdn.n...",[],NaN,0,https://instagram.fsjc1-3.fna.fbcdn.net/o1/v/t...
514,https://www.instagram.com/p/DNdKANzS4jr,ravisagar88,😭😭 @simran_viral_creator,NaN,3109,2025-08-17T12:08:12.000Z,133477.0,"[""https://scontent-dfw5-2.cdninstagram.com/v/t...",NaN,NaN,...,"{""profile_id"":null,""profile_url"":null,""usernam...",9600721638,"[{""id"":""3701158464052758763"",""index"":0,""type"":...","{""audio_asset_id"":null,""ig_artist_id"":null,""ig...",https://www.instagram.com/ravisagar88,NaN,[],"Photo by Ravi Kumar on August 17, 2025. May be...",0,NaN
141,https://www.instagram.com/p/Bgs2JIFnnFO,dilettaleotta,😻,NaN,572,2018-03-24T09:20:33.000Z,129951.0,"[""https://instagram.fsjc1-3.fna.fbcdn.net/v/t5...",NaN,"[""Villa Borromeo d'Adda""]",...,"{""profile_id"":null,""profile_url"":null,""usernam...",345533865,"[{""id"":""1742005277556633934"",""index"":0,""type"":...","{""audio_asset_id"":null,""ig_artist_id"":null,""ig...",https://www.instagram.com/dilettaleotta,NaN,[],Photo by 🌸Diletta Leotta🌸 in Villa Borromeo d'...,0,NaN
96,https://www.instagram.com/p/DJZxxi8OHf0,amybethmcnulty,A night to remember in Venice.. at “Altered St...,"[""#GoldenGoose"",""#HAUSofDreamers""]",199,2025-05-08T18:33:11.000Z,123346.0,"[""https://scontent-atl3-1.cdninstagram.com/v/t...",NaN,"[""Venice"",""Italy""]",...,"{""profile_id"":null,""profile_url"":null,""usernam...",2281529693,"[{""alt_text"":""Photo by Amybeth on May 08, 2025...","{""audio_asset_id"":null,""ig_artist_id"":null,""ig...",https://www.instagram.com/amybethmcnulty,NaN,"[{""id"":""362***987***221******"",""url"":""htt***//...","Photo by Amybeth on May 08, 2025.",8,NaN
14,https://www.instagram.com/p/C58N0aMLHq0,premierleague,Who is the best of these six young attacking m...,"[""#RisingStars,""]",1803,2024-04-19T11:10:07.000Z,119746.0,"[""https://scontent-lga3-3.cdninstagram.com/v/t...",NaN,NaN,...,"{""profile_id"":""241666002"",""profile_url"":""https...",208502444,"[{""id"":""3349612998995770036"",""index"":0,""type"":...","{""audio_asset_id"":null,""ig_artist_id"":null,""ig...",https://www.instagram.com/premierleague,NaN,[],"Photo by Premier League on April 19, 2024.",0,NaN
57,https://www.instagram.com/p/DLQkzuGOgw-,somosinvictos,"Y sí, sucedió. Por primera vez en toda su carr...","[""#julian"",""#atletico"",""#araña"",""#argentina"",""...",1260,2025-06-23T21:49:31.000Z,111881.0,"[""https://instagram.fsjc1-3.fna.fbcdn.net/v/t5...",NaN,NaN,...,"{""profile_id"":null,""profile_url"":null,""usernam...",573632344,"[{""id"":""3661588380916517950"",""index"":0,""type"":...","{""audio_asset_id"":null,""ig_artist_id"":null,""ig...",https://www.instagram.com/somosinvictos,NaN,[],"Photo by Invictos on June 23, 2025.",0,NaN
678,https://www.instagram.com/p/DPJeg10D1JR,aajtak,41 साल के एशिया कप इतिहास में पहली बार भारत और...,"[""#AsiaCup2025"",""#IndVsPak"",""#TeamIndia"",""#Cri...",825,2025-09-28T13:45:24.000Z,91931.0,"[""https://scontent.cdninstagram.com/v/t51.2885...",NaN,NaN,...,"{""profile_id"":null,""profile_url"":null,""usernam...",3160772264,"[{""id"":""3731647964453491281"",""index"":0,""type"":...","{""audio_asset_id"":null,""ig_artist_id"":null,""ig...",https://www.instagram.com/aajtak,NaN,[],"Photo by Aaj Tak on September 28, 2025. May be...",0,NaN

In [28]:
df.describe(include="all")

,url,user_posted,description,hashtags,num_comments,date_posted,likes,photos,videos,location,...,partnership_details,user_posted_id,post_content,audio,profile_url,videos_duration,images,alt_text,photos_number,audio_url
count,1000,1000,956,647,1000.000000,1000,888.000000,1000,179,276,...,1000,1.000000e+03,1000,1000,1000,231,1000,868,1000.000000,17
unique,1000,994,956,647,NaN,1000,NaN,1000,179,264,...,5,NaN,1000,105,994,178,367,868,NaN,17
top,https://www.instagram.com/p/DD9dlUXTvTf,stratfordinternational,A Christmas Note for you all..⁠\n⁠\nIt's been ...,"[""#christmasmessage"",""#thankyou""]",NaN,2024-12-24T12:01:05.000Z,NaN,"[""https://scontent-lga3-1.cdninstagram.com/v/t...","[""https://scontent-ord5-1.cdninstagram.com/o1/...","[""Nashville"",""Tennessee""]",...,"{""profile_id"":null,""profile_url"":null,""usernam...",NaN,"[{""alt_text"":""Photo by Made By Coopers | Aroma...","{""audio_asset_id"":null,""ig_artist_id"":null,""ig...",https://www.instagram.com/stratfordinternational,[],[],Photo by Made By Coopers | Aromatherapy & Skin...,NaN,https://scontent-lax3-2.cdninstagram.com/o1/v/...
freq,1,2,1,1,NaN,1,NaN,1,1,3,...,996,NaN,1,895,2,54,634,1,NaN,1
mean,NaN,NaN,NaN,NaN,44.703000,NaN,3601.032658,NaN,NaN,NaN,...,NaN,1.302082e+10,NaN,NaN,NaN,NaN,NaN,NaN,1.983000,NaN
std,NaN,NaN,NaN,NaN,289.961474,NaN,24056.196350,NaN,NaN,NaN,...,NaN,1.932481e+10,NaN,NaN,NaN,NaN,NaN,NaN,3.461892,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,NaN,NaN,...,NaN,1.818360e+05,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
25%,NaN,NaN,NaN,NaN,0.000000,NaN,12.000000,NaN,NaN,NaN,...,NaN,1.196762e+09,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
50%,NaN,NaN,NaN,NaN,1.000000,NaN,73.000000,NaN,NaN,NaN,...,NaN,3.600238e+09,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
75%,NaN,NaN,NaN,NaN,12.000000,NaN,452.750000,NaN,NaN,NaN,...,NaN,1.168076e+10,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN
max,NaN,NaN,NaN,NaN,6158.000000,NaN,425076.000000,NaN,NaN,NaN,...,NaN,7.736041e+10,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,NaN


# **DS2**

Instagram Reel dataset (DS2) - [Instagram-Reels.csv](https://brightdata.com/cp/datasets/browse/gd_lyclm20il4r5helnj?id=hl_6c69a494)

Strengths:

* Directly supports video-specific analysis with complete length (duration in seconds, mean 60s, no missing values) and strong engagement metrics like views (mean ~73k, up to 25M) and video_play_count.
​

* Full coverage of core fields like date_posted, likes, num_comments, enabling easy extraction of posting time and hashtag counts (from hashtags, 65.6% non-null).
​

* Includes creator context (followers, is_verified) for normalizing virality by audience size.
​

Weaknesses:

* High missingness in followers (48.1%) and posts_count (48.1%), limiting audience-adjusted models unless imputed.
​

* Data quality issues like negative likes values and extreme outliers (e.g., views std ~826k), requiring cleaning and log-transformation.
​

* No explicit "trending audio" flag; audio_url needs frequency-based proxy.

In [29]:
df = pd.read_csv('Instagram - Reels.csv')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   url                  1000 non-null   object
 1   user_posted          1000 non-null   object
 2   description          956 non-null    object
 3   hashtags             656 non-null    object
 4   num_comments         1000 non-null   int64
 5   date_posted          1000 non-null   object
 6   likes                1000 non-null   int64
 7   views                1000 non-null   int64
 8   video_play_count     984 non-null    float64
 9   top_comments         1000 non-null   object
 10  post_id              1000 non-null   object
 11  thumbnail            1000 non-null   object
 12  shortcode            1000 non-null   object
 13  content_id           1000 non-null   object
 14  product_type         1000 non-null   object
 15  coauthor_producers   1000 non-null   object
 16  tagged_users         1000 non-null   object
 17  length               1000 non-null   float64
 18  video_url            1000 non-null   object
 19  audio_url            952 non-null    object
 20  posts_count          519 non-null    float64
 21  followers            519 non-null    float64
 22  following            0 non-null      float64
 23  user_profile_url     1000 non-null   object
 24  is_paid_partnership  1000 non-null   bool
 25  is_verified          1000 non-null   bool
 26  profile_image_link   999 non-null    object
dtypes: bool(2), float64(5), int64(3), object(17)
memory usage: 197.4+ KB

In [31]:
df.sort_values(by='likes', ascending=False).head(10)

,url,user_posted,description,hashtags,num_comments,date_posted,likes,views,video_play_count,top_comments,...,length,video_url,audio_url,posts_count,followers,following,user_profile_url,is_paid_partnership,is_verified,profile_image_link
899,https://www.instagram.com/reel/DH5tG4NP5Nu/,aarushbhola17,🥰🥰🥰,NaN,10308,2025-04-01T11:06:07.000Z,3009655,24942177,55252656.0,"[{""avatar"":""https://scontent-ord5-3.cdninstagr...",...,20.533,https://scontent-ord5-3.cdninstagram.com/o1/v/...,https://www.instagram.com/reels/audio/15735643...,2588.0,4349695.0,NaN,htt***//w***ins*********m/a***************,False,True,https://instagram.fcjs4-1.fna.fbcdn.net/v/t51....
765,https://www.instagram.com/reel/COgeRQ1CF1u/,fcbarcelona,🎯 Free kick GOLAZO! 🚀 \n\n💙❤️ @fcbfemeni,NaN,1058,2021-05-05T22:05:26.000Z,468277,3234312,NaN,"[{""avatar"":""https://instagram.fphl1-1.fna.fbcd...",...,12.400,https://instagram.fphl1-1.fna.fbcdn.net/o1/v/t...,NaN,NaN,NaN,NaN,htt***//w***ins*********m/f************,False,True,https://instagram.fphl1-1.fna.fbcdn.net/v/t51....
646,https://www.instagram.com/reel/BVNWakrDAQQ/,natgeo,Video by @renan_ozturk @davemossop // A time-l...,"[""#intothemind"",""#NepaliLoveYou""]",2062,2017-06-11T18:01:31.000Z,453185,0,NaN,"[{""avatar"":""https://scontent.cdninstagram.com/...",...,14.433,https://scontent.cdninstagram.com/o1/v/t16/f2/...,NaN,NaN,NaN,NaN,htt***//w***ins*********m/n******,False,True,https://scontent.cdninstagram.com/v/t51.2885-1...
713,https://www.instagram.com/reel/DHyBYjGNRM9/,dev.mishra_ak47,🙋~Dad 💪 Beti 🥰 Beta 😍 Mom 💖 Love Family 👨‍👩‍👧‍...,"[""#devmishraak47"",""#devmishra"",""#🇮🇳👑💪"",""#india...",1189,2025-03-29T11:34:05.000Z,300524,2133544,6584953.0,"[{""avatar"":""https://scontent-sjc6-1.cdninstagr...",...,15.000,https://scontent-sjc3-1.cdninstagram.com/o1/v/...,https://www.instagram.com/reels/audio/76209507...,265.0,579078.0,NaN,htt***//w***ins*********m/d***************,False,False,https://scontent-mia3-1.cdninstagram.com/v/t51...
239,https://www.instagram.com/reel/C-e39tIPyeJ/,ashwilliams1,"Breakdance, not hearts #olympics #paris2024 #b...","[""#olympics"",""#paris2024"",""#breakdance"",""#rayg...",8929,2024-08-10T08:18:50.000Z,264697,4412982,11012602.0,"[{""avatar"":""https://scontent-dfw5-1.cdninstagr...",...,32.400,https://scontent-dfw5-1.cdninstagram.com/o1/v/...,https://www.instagram.com/reels/audio/84777238...,2242.0,90599.0,NaN,htt***//w***ins*********m/a************,False,True,https://instagram.fgdl17-1.fna.fbcdn.net/v/t51...
359,https://www.instagram.com/reel/DG-eT2zR8MU/,ateez_official_,#WOOYOUNG in COURREGES FW25 SHOW\n\n#ATEEZ #에이...,"[""#WOOYOUNG"",""#ATEEZ"",""#에이티즈"",""#우영"",""#courrege...",1940,2025-03-09T11:00:00.000Z,234571,297438,1348832.0,"[{""avatar"":""https://scontent.cdninstagram.com/...",...,49.549,https://scontent.cdninstagram.com/o1/v/t2/f2/m...,https://www.instagram.com/reels/audio/26220378...,NaN,NaN,NaN,htt***//w***ins*********m/a***************,False,True,https://scontent.cdninstagram.com/v/t51.2885-1...
295,https://www.instagram.com/reel/CnuuDLRANvt/,espnmma,Is Pereira eyeing LHW gold? 🏆 #UFC283 \n\n(h/t...,"[""#UFC283""]",1875,2023-01-22T20:05:40.000Z,225284,2096782,3259759.0,"[{""avatar"":""https://scontent.cdninstagram.com/...",...,11.200,https://scontent.cdninstagram.com/o1/v/t2/f2/m...,https://www.instagram.com/reels/audio/15077735...,NaN,NaN,NaN,htt***//w***ins*********m/e*********,False,True,https://scontent.cdninstagram.com/v/t51.2885-1...
170,https://www.instagram.com/reel/C-XkhoGINSq/,xiaomi.global,👀 What's that!\n#Xiaomi14Ultra #LensToLegend,"[""#Xiaomi14Ultra"",""#LensToLegend""]",36,2024-08-07T12:13:49.000Z,211289,343555,1422057.0,"[{""avatar"":""https://scontent-dfw5-1.cdninstagr...",...,10.479,https://scontent-dfw5-3.cdninstagram.com/o1/v/...,https://www.instagram.com/reels/audio/32016767...,1742.0,4973824.0,NaN,htt***//w***ins*********m/x***************,False,True,https://scontent-den2-1.cdninstagram.com/v/t51...
729,https://www.instagram.com/reel/C_Hi4Mmt_Ia/,tianasari874,Emang agak lain sih Dika ini😅,NaN,2500,2024-08-26T03:24:13.000Z,165841,0,3240263.0,"[{""avatar"":""https://scontent-dfw5-1.cdninstagr...",...,55.396,https://scontent-dfw6-1.cdninstagram.com/o1/v/...,https://www.instagram.com/reels/audio/88611157...,171.0,138896.0,NaN,htt***//w***ins*********m/t************,False,False,https://scontent-atl3-3.cdninstagram.com/v/t51...
251,https://www.instagram.com/reel/CQvi7fiFH1o/,snoopdogg,Part 1💨💫🤣,NaN,1291,2021-06-30T11:37:32.000Z,160828,1710209,NaN,"[{""avatar"":""https://scontent-bos5-1.cdninstagr...",...,20.066,https://scontent-bos5-1.cdninstagram.com/o1/v/...,NaN,NaN,NaN,NaN,htt***//w***ins*********m/s*********,False,True,https://scontent-bos5-1.cdninstagram.com/v/t51...

In [32]:
df.describe(include="all")

,url,user_posted,description,hashtags,num_comments,date_posted,likes,views,video_play_count,top_comments,...,length,video_url,audio_url,posts_count,followers,following,user_profile_url,is_paid_partnership,is_verified,profile_image_link
count,1000,1000,956,656,1000.000000,1000,1.000000e+03,1.000000e+03,9.840000e+02,1000,...,1000.000000,1000,952,519.000000,5.190000e+02,0.0,1000,1000,1000,999
unique,1000,995,955,655,NaN,1000,NaN,NaN,NaN,783,...,NaN,1000,922,NaN,NaN,NaN,169,2,2,999
top,https://www.instagram.com/reel/C7ULNWMMqUy/,jaat_nia,❤️,"[""#reelsinstagram""]",NaN,2024-05-23T15:03:16.000Z,NaN,NaN,NaN,[],...,NaN,https://instagram.fsjc1-3.fna.fbcdn.net/o1/v/t...,https://www.instagram.com/reels/audio/0,NaN,NaN,NaN,htt***//w***ins*********m/a***************,False,False,https://instagram.fman4-2.fna.fbcdn.net/v/t51....
freq,1,2,2,2,NaN,1,NaN,NaN,NaN,218,...,NaN,1,21,NaN,NaN,NaN,35,993,593,1
mean,NaN,NaN,NaN,NaN,82.820000,NaN,9.544864e+03,7.268415e+04,1.964173e+05,NaN,...,59.838392,NaN,NaN,7960.788054,4.749622e+05,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,484.452313,NaN,9.991416e+04,8.255721e+05,1.841414e+06,NaN,...,209.122460,NaN,NaN,20192.082484,2.107900e+06,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,-1.000000e+00,0.000000e+00,3.000000e+00,NaN,...,1.000000,NaN,NaN,11.000000,2.400000e+01,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,1.000000,NaN,2.700000e+01,1.697500e+02,2.671000e+03,NaN,...,15.764000,NaN,NaN,789.000000,1.677800e+04,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,7.000000,NaN,1.855000e+02,1.443500e+03,1.139300e+04,NaN,...,30.684500,NaN,NaN,1901.000000,8.009100e+04,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,31.000000,NaN,1.462750e+03,1.053525e+04,5.992600e+04,NaN,...,57.220000,NaN,NaN,5480.000000,2.772295e+05,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,10308.000000,NaN,3.009655e+06,2.494218e+07,5.525266e+07,NaN,...,3608.136000,NaN,NaN,168047.000000,3.620239e+07,NaN,NaN,NaN,NaN,NaN

# **DS3**

Instagram generic dataset (DS3) - [Instagram-datasets.csv](https://github.com/luminati-io/Social-media-dataset-samples/blob/main/Instagram-datasets.csvhttps://github.com/luminati-io/Social-media-dataset-samples/blob/main/Instagram-datasets.csv)

Strengths:


*   Near-perfect completeness (0% missing in core columns like likes_number, replies_number, comment_date, post_id), ideal for aggregating comment engagement per post.

*  Enables label enrichment (e.g., comments as virality signal) via post_id joins.


* Low skew in metrics (e.g., likes_number mean 3.7), stable for summaries.


Weaknesses:

* Lacks post characteristics (no duration, hashtags, audio), only useful as an extension.
​

* High missingness in hashtag_comment (99.4%) and tagged_users_in_comment (85.4%), limiting content analysis from comments.
​

* Potential selection bias: only commented posts, skewing toward higher-engagement content.

In [33]:
df = pd.read_csv('Instagram-datasets.csv')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   url                      1000 non-null   object
 1   comment_user             1000 non-null   object
 2   comment_user_url         1000 non-null   object
 3   comment_date             1000 non-null   object
 4   comment                  1000 non-null   object
 5   likes_number             1000 non-null   int64
 6   replies_number           1000 non-null   int64
 7   replies                  998 non-null    object
 8   hashtag_comment          6 non-null      object
 9   tagged_users_in_comment  146 non-null    object
 10  post_url                 1000 non-null   object
 11  post_user                1000 non-null   object
 12  comment_id               1000 non-null   int64
 13  post_id                  1000 non-null   int64
dtypes: int64(4), object(10)
memory usage: 109.5+ KB

In [35]:
df.sort_values(by='likes_number', ascending=False).head(10)

,url,comment_user,comment_user_url,comment_date,comment,likes_number,replies_number,replies,hashtag_comment,tagged_users_in_comment,post_url,post_user,comment_id,post_id
195,https://www.instagram.com/mahamfatima,ooo███zin███oo,https://www.instagram.com/oooamazingoooo,2024-08-10T16:21:05.000Z,"Yes, remember why they were punished and judge...",2116,1,"[{""likes_number"":10,""reply"":""@_michaelfabian_ ...",NaN,NaN,https://www.instagram.com/p/C-amNtlx321,mah███ati███,17927532056920578,3430222134268886453
802,https://www.instagram.com/motorsportcom,agg███kiu███,https://www.instagram.com/aggie.kiux,2024-10-25T08:31:32.000Z,"Ferrari is a rollercoaster of emotions, but th...",127,1,"[{""likes_number"":2,""reply"":""yea as a closeted ...",NaN,NaN,https://www.instagram.com/p/DBiiU4rtV9N,mot███por███m,18317711623080237,3486500030371946317
785,https://www.instagram.com/motorsportcom,ape███red███r_v█████████,https://www.instagram.com/apex_predator_viper009,2024-11-14T07:53:54.000Z,Carlos Looks like a Prince!!,44,1,"[{""likes_number"":1,""reply"":""@apex_predator_vip...",NaN,NaN,https://www.instagram.com/p/DCV-xy0tBsQ,mot███por███m,17989113635727867,3500980386059787024
794,https://www.instagram.com/motorsportcom,ian███17,https://www.instagram.com/ian_a117,2024-11-07T17:54:19.000Z,Pole by over a second on a wet track..,41,1,"[{""likes_number"":1,""reply"":""@ian_a117 in a wil...",NaN,NaN,https://www.instagram.com/p/DCETQGVNpMS,mot███por███m,17854205835315054,3496003879940035346
792,https://www.instagram.com/motorsportcom,com███ika███,https://www.instagram.com/comtopikachu,2024-11-15T20:05:15.000Z,Poor Charles! No one imitates him. It's like a...,34,1,"[{""likes_number"":2,""reply"":""@comtopikachu yes ...",NaN,NaN,https://www.instagram.com/reel/DCZb6W7MbMj,mot███por███m,17904758394001150,3501952942858154787
913,https://www.instagram.com/adhouseplans,sav███ahs███cer███,https://www.instagram.com/savannahspencer1,2024-11-12T01:36:07.000Z,I don’t need the sign I need the money 😂 @seth...,18,1,"[{""likes_number"":1,""reply"":""@savannahspencer1 ...",NaN,"[""@se███spe███r12███""]",https://www.instagram.com/reel/DCPttimSPQb,adh███epl███,18062825740784148,3499216477109154843
938,https://www.instagram.com/nyxcosmetics,boo███oli███1,https://www.instagram.com/bookaholic711,2024-11-19T15:30:47.000Z,All I can think is....all of the people who wi...,16,1,"[{""likes_number"":1,""reply"":""@bookaholic711 Noo...",NaN,NaN,https://www.instagram.com/reel/DCH36bLPf4J,nyx███met███,17859920634290900,3497009543143882249
791,https://www.instagram.com/motorsportcom,for███aon███rlc███,https://www.instagram.com/formulaonegirlcl,2024-11-04T18:06:05.000Z,We need it international please 🔥,12,1,"[{""likes_number"":4,""reply"":""@formulaonegirlcl ...",NaN,NaN,https://www.instagram.com/p/DB9SWLoO4nK,mot███por███m,17879892183171953,3494029575061211594
786,https://www.instagram.com/motorsportcom,___███2_2███,https://www.instagram.com/_____62_20,2024-11-11T19:16:43.000Z,The gearboxes of MotoGP bikes are insane. Watc...,10,1,"[{""likes_number"":0,""reply"":""I remember the tim...",NaN,NaN,https://www.instagram.com/p/DCPf_dGMh3s,mot███por███m,17948130488860968,3499156135501503980
890,https://www.instagram.com/nyxcosmetics,gov███ame███,https://www.instagram.com/govt.name,2024-11-07T07:48:34.000Z,that black shade is looking real warm medium b...,9,1,"[{""likes_number"":1,""reply"":""Sadly that feels l...",NaN,NaN,https://www.instagram.com/reel/DB_06XLykXT,nyx███met███,17979229724781179,3494744544904889811

In [36]:
df.describe(include="all")

,url,comment_user,comment_user_url,comment_date,comment,likes_number,replies_number,replies,hashtag_comment,tagged_users_in_comment,post_url,post_user,comment_id,post_id
count,1000,1000,1000,1000,1000,1000.000000,1000.000000,998,6,146,1000,1000,1.000000e+03,1.000000e+03
unique,273,929,929,1000,901,NaN,NaN,996,6,137,555,273,NaN,NaN
top,https://www.instagram.com/nyxcosmetics,liv███nla███gas███,https://www.instagram.com/livingnlasvegas,2024-12-12T11:22:02.000Z,👏👏👏,NaN,NaN,[],"[""#First"",""#Best""]","[""@_c███lin███yle███""]",https://www.instagram.com/p/Cyd6kDrIBwN,nyx███met███,NaN,NaN
freq,43,6,6,1,17,NaN,NaN,3,1,3,5,43,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,3.733000,1.168000,NaN,NaN,NaN,NaN,NaN,1.803215e+16,3.276172e+18
std,NaN,NaN,NaN,NaN,NaN,67.024578,0.562221,NaN,NaN,NaN,NaN,NaN,1.304669e+14,3.513892e+17
min,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,1.784211e+16,1.547983e+18
25%,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.794634e+16,3.234987e+18
50%,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.802367e+16,3.419599e+18
75%,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.806544e+16,3.497107e+18
max,NaN,NaN,NaN,NaN,NaN,2116.000000,6.000000,NaN,NaN,NaN,NaN,NaN,1.847655e+16,3.522242e+18