# Question: What is the relationship between specific post characteristics (like video duration, use of trending audio, posting time, and hashtag count) and the likelihood of a post achieving viral status on Social Media?

## Relevant Facebook statistics

what we want is meta data and engagement metrics in order to define or approximate viral status

* Demonstrate the relevance of these sources using initial exploration, such as summary statistics, schema inspection, or simple exploratory analysis.
*   Brief description of downloaded data and reflection on how well it matches requirements or how it is amenable to match the requirements.
*   Profiling steps that should include a short description, the code to execute these, and an interpretation and critical discussion of the results with respect to the suitability of the dataset for addressing the analytical task.
* Discussion of the quality of the data relating to aspects to be considered during data preparation and analysis. It should refer to at least two different quality criteria per explored dataset, one beign assessed positively and one assessed as problematic.
* Concluding paragraph that summarizes suitability and important points to take note of if the dataset is selected to be used.

*** Bright data has the full set of youtube posts metadata, which is similar to DS2, but its locked behind a paywall :(

## DS1

[Facebook Text Classification (DS1) - Facebook_data_txt.csv](https://www.kaggle.com/datasets/kalashnikov1405/facebook-text-classification)

The dataset contains Facebook post data, in particular text classification.

(Definition of text classification:
It is a labeled collection of text data (sentences or documents) paired with predefined categories, used to train machine learning models to automatically categorize future, unseen text.)

Strengths:
* Has many useful attributes that directly measures how viral a post is as well as the post's corresponding properties. For example, the timestamp, engagement metrics and sentiment will be helpful here.
* There may be potential for modelling of content popularity for prediction by using the likes, comments, shares data.
* Useful to identify text to be used in posts that can give the most chance of making it viral.

Weaknesses:
* Does not have any information related to videos, as it only focuses on text-based media.

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('Facebook_data_txt.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   post_id    5000 non-null   int64
 1   timestamp  5000 non-null   object
 2   text       5000 non-null   object
 3   category   5000 non-null   object
 4   sentiment  5000 non-null   object
 5   language   5000 non-null   object
 6   has_link   5000 non-null   int64
 7   likes      5000 non-null   int64
 8   comments   5000 non-null   int64
 9   shares     5000 non-null   int64
 10  is_spam    5000 non-null   int64
dtypes: int64(6), object(5)
memory usage: 429.8+ KB

In [7]:
# change the by to likes,comments,shares etc
df.sort_values(by='likes', ascending=False).head(10)

,post_id,timestamp,text,category,sentiment,language,has_link,likes,comments,shares,is_spam
1431,3278,2023-07-15 04:05:00,Friend: ‘We should work out.’ Us: 🎉,meme_joke,positive,en,0,170,21,48,0
1137,2396,2024-02-17 16:59:00,When you open the fridge and forget why you ca...,meme_joke,positive,en,0,169,40,39,0
786,3928,2024-08-05 07:36:00,Friend: ‘We should work out.’ Us: 🔥,meme_joke,positive,fr,0,169,53,23,0
2615,1550,2023-12-25 12:10:00,POV: You at 8am meetings 🎉🎉,meme_joke,positive,en,1,169,64,49,0
2529,4604,2023-09-01 21:02:00,When you open the fridge and forget why you ca...,meme_joke,positive,en,0,167,27,43,0
1016,100,2024-08-26 05:24:00,Me: I’ll sleep early. Also me at 3am: 😀,meme_joke,positive,en,0,167,56,17,0
3817,4141,2025-04-13 19:18:00,POV: You at 8am meetings 🤔🤔,meme_joke,positive,es,1,167,47,47,0
1323,858,2023-07-30 12:42:00,Friend: ‘We should work out.’ Us: 😀,meme_joke,positive,en,0,167,47,18,0
2880,2346,2023-05-20 08:09:00,POV: You at 8am meetings 💖💖,meme_joke,positive,en,0,167,45,34,0
2673,4083,2023-08-15 09:19:00,Me: I’ll sleep early. Also me at 3am: 🤔,meme_joke,positive,hi,1,166,39,10,0

In [14]:
df.describe(include="all")

,post_id,timestamp,text,category,sentiment,language,has_link,likes,comments,shares,is_spam
count,5000.000000,5000,5000,5000,5000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
unique,NaN,4988,1639,10,3,5,NaN,NaN,NaN,NaN,NaN
top,NaN,2023-07-04 14:07:00,Debate tonight on privacy law. What are your t...,personal_update,positive,en,NaN,NaN,NaN,NaN,NaN
freq,NaN,2,32,985,2253,2737,NaN,NaN,NaN,NaN,NaN
mean,2500.500000,NaN,NaN,NaN,NaN,NaN,0.301400,46.487200,11.183600,7.635600,0.021000
std,1443.520003,NaN,NaN,NaN,NaN,NaN,0.458912,33.785389,10.027901,7.245724,0.143398
min,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1250.750000,NaN,NaN,NaN,NaN,NaN,0.000000,19.000000,4.000000,2.000000,0.000000
50%,2500.500000,NaN,NaN,NaN,NaN,NaN,0.000000,39.000000,8.000000,5.000000,0.000000
75%,3750.250000,NaN,NaN,NaN,NaN,NaN,1.000000,65.000000,16.000000,11.000000,0.000000
max,5000.000000,NaN,NaN,NaN,NaN,NaN,1.000000,170.000000,64.000000,49.000000,1.000000

## DS2

[Facebook posts dataset Bright Data (DS2) - facebook-posts-by-profile.csv](https://github.com/luminati-io/Facebook-dataset-samples/blob/main/facebook-posts-by-profile.csv)

The dataset is very comprehensive: It covers a wide area of content like posts, reels, events and comments. Hashtags and engagement metrics can be analyzed. We can also examine user interactions like using likes and replies to improve virality.


Strengths:
* Contains many useful attributes for further analysis
* Has multiple post formats
* Has post date and specific time so we can see the time of day effects for a post
* Since I believe its part of the official dataset, this data should be comprehensive and useful

Weaknesses:
* Still lacks video duration and audio information, so we cannot fully study what makes a video viral
* Has quite a lot of null attributes, and date format needs to be standardised, meaning needs some data processing

In [8]:
df = pd.read_csv('facebook-posts-by-profile.csv')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 38 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   url                    1000 non-null   object
 1   post_id                1000 non-null   int64
 2   user_url               1000 non-null   object
 3   user_username_raw      1000 non-null   object
 4   content                984 non-null    object
 5   date_posted            1000 non-null   object
 6   hashtags               984 non-null    object
 7   num_comments           1000 non-null   int64
 8   num_shares             1000 non-null   int64
 9   num_likes_type         988 non-null    object
 10  page_name              1000 non-null   object
 11  page_intro             0 non-null      float64
 12  page_category          0 non-null      float64
 13  page_logo              1000 non-null   object
 14  page_external_website  0 non-null      float64
 15  page_likes             950 non-null    float64
 16  page_followers         1000 non-null   int64
 17  page_is_verified       1000 non-null   bool
 18  original_post          13 non-null     object
 19  other_posts_url        0 non-null      float64
 20  post_external_link     105 non-null    object
 21  post_external_title    105 non-null    object
 22  page_url               1000 non-null   object
 23  header_image           1000 non-null   object
 24  profile_id             1000 non-null   int64
 25  attachments            1000 non-null   object
 26  avatar_image_url       1000 non-null   object
 27  profile_handle         1000 non-null   object
 28  has_handshake          0 non-null      float64
 29  is_sponsored           1000 non-null   bool
 30  sponsor_name           0 non-null      float64
 31  shortcode              1000 non-null   int64
 32  video_view_count       334 non-null    float64
 33  likes                  988 non-null    float64
 34  post_image             533 non-null    object
 35  post_type              1000 non-null   object
 36  following              50 non-null     float64
 37  post_external_image    0 non-null      float64
dtypes: bool(2), float64(11), int64(6), object(19)
memory usage: 283.3+ KB

In [10]:
df.describe()

,post_id,num_comments,num_shares,page_intro,page_category,page_external_website,page_likes,page_followers,other_posts_url,profile_id,has_handshake,sponsor_name,shortcode,video_view_count,likes,following,post_external_image
count,1.000000e+03,1000.000000,1000.000000,0.0,0.0,0.0,9.500000e+02,1.000000e+03,0.0,1.000000e+03,0.0,0.0,1.000000e+03,3.340000e+02,988.000000,50.00000,0.0
mean,4.381055e+15,987.842000,897.273000,NaN,NaN,NaN,1.941064e+08,2.120672e+08,NaN,1.000461e+14,NaN,NaN,4.381055e+15,2.795916e+05,5391.117409,79.42000,NaN
std,3.051308e+15,2153.390746,2498.139281,NaN,NaN,NaN,3.383747e+07,6.168563e+07,NaN,5.388342e+09,NaN,NaN,3.051308e+15,6.618458e+05,9447.981983,73.64839,NaN
min,1.270469e+14,0.000000,0.000000,NaN,NaN,NaN,3.600000e+01,3.800000e+01,NaN,1.000338e+14,NaN,NaN,1.270469e+14,8.600000e+01,1.000000,1.00000,NaN
25%,1.029286e+15,82.500000,40.750000,NaN,NaN,NaN,2.000000e+08,2.300000e+08,NaN,1.000446e+14,NaN,NaN,1.029286e+15,2.421850e+04,512.000000,27.75000,NaN
50%,7.072014e+15,301.000000,179.000000,NaN,NaN,NaN,2.000000e+08,2.300000e+08,NaN,1.000446e+14,NaN,NaN,7.072014e+15,7.621000e+04,1906.000000,51.50000,NaN
75%,7.139208e+15,958.000000,704.250000,NaN,NaN,NaN,2.000000e+08,2.300000e+08,NaN,1.000446e+14,NaN,NaN,7.139208e+15,2.150870e+05,5733.500000,111.25000,NaN
max,1.016096e+16,23055.000000,35082.000000,NaN,NaN,NaN,2.000000e+08,2.300000e+08,NaN,1.000763e+14,NaN,NaN,1.016096e+16,6.173730e+06,88521.000000,278.00000,NaN

## DS3

[Facebook Metrics Data (DS3) - Facebook Metrics of Cosmetic Brand.csv](https://www.kaggle.com/datasets/dileeppatchaone/facebook-metrics-dataset-of-cosmetic-brand)

This dataset comes from a cosmetics brand page and contains performance metrics for Facebook posts published over a year. It has no null values and includes about 500 posts with various engagement and metadata metrics, basically the usual likes, shares and comments etc.

Strengths:
* Also relevant to engagement virality analysis.
* Has temporal data as well
* Has a lifetime post data that might be helpful

Weaknesses:
* Not sure about its usefulness / relevance to the overarching theme which is that this is solely about cosmetics, and maybe our topic is about entertainment?
* Also does not have multimedia data
* Small sample of around 500 posts

In [11]:
df = pd.read_csv('Facebook Metrics of Cosmetic Brand.csv')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Unnamed: 0                                                           500 non-null    int64
 1   Page total likes                                                     500 non-null    int64
 2   Type                                                                 500 non-null    object
 3   Category                                                             500 non-null    int64
 4   Post Month                                                           500 non-null    int64
 5   Post Weekday                                                         500 non-null    int64
 6   Post Hour                                                            500 non-null    int64
 7   Paid                                                                 499 non-null    float64
 8   Lifetime Post Total Reach                                            500 non-null    int64
 9   Lifetime Post Total Impressions                                      500 non-null    int64
 10  Lifetime Engaged Users                                               500 non-null    int64
 11  Lifetime Post Consumers                                              500 non-null    int64
 12  Lifetime Post Consumptions                                           500 non-null    int64
 13  Lifetime Post Impressions by people who have liked your Page         500 non-null    int64
 14  Lifetime Post reach by people who like your Page                     500 non-null    int64
 15  Lifetime People who have liked your Page and engaged with your post  500 non-null    int64
 16  comment                                                              500 non-null    int64
 17  like                                                                 499 non-null    float64
 18  share                                                                496 non-null    float64
 19  Total Interactions                                                   500 non-null    int64
dtypes: float64(3), int64(16), object(1)
memory usage: 78.3+ KB

In [12]:
df.describe()

,Unnamed: 0,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,249.500000,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,144.481833,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,0.000000,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,124.750000,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,249.500000,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,374.250000,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,499.000000,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000